# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CashctlRc < Formula
  desc "Release-candidate build of cashctl -- see the cashctl formula for stable installs."
  homepage "https://github.com/ohstr/cashctl"
  version "0.6.0-rc.1"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohstr/cashctl/releases/download/v0.6.0-rc.1/cashctl_darwin_amd64.tar.gz"
      sha256 "205e0da0399fa1f2c4a1edcc7515e1c29e33eb0dee3210c2081f1534a3f73a06"

      define_method(:install) do
        bin.install "cashctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohstr/cashctl/releases/download/v0.6.0-rc.1/cashctl_darwin_arm64.tar.gz"
      sha256 "8bc680afb0bf5b4cabeef41e019faf6dd5a7660d89ef52c0c30260bdf3d97cd1"

      define_method(:install) do
        bin.install "cashctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/cashctl/releases/download/v0.6.0-rc.1/cashctl_linux_amd64.tar.gz"
      sha256 "1916e8cfcff68d6c034a19508286f75c60c109d4486b9a16ec81f1a646231aa0"
      define_method(:install) do
        bin.install "cashctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/cashctl/releases/download/v0.6.0-rc.1/cashctl_linux_arm64.tar.gz"
      sha256 "864c8ceabd830c0742a312c60e7e2cb51deaef001f2d7b558cdfb336ce8560a1"
      define_method(:install) do
        bin.install "cashctl"
      end
    end
  end

  conflicts_with "cashctl"

  test do
    system "#{bin}/cashctl", "version"
  end
end
