# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cashctl < Formula
  desc "A wallet CLI for NIP-CASH cash tokens and NIP-CW circle wallets."
  homepage "https://github.com/ohstr/cashctl"
  version "0.4.0"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohstr/cashctl/releases/download/v0.4.0/cashctl_darwin_amd64.tar.gz"
      sha256 "8dd2e4cd2aa9c2289fbf6cbc8694691a2af9feecff765327bf0e63d4bc534c7c"

      define_method(:install) do
        bin.install "cashctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohstr/cashctl/releases/download/v0.4.0/cashctl_darwin_arm64.tar.gz"
      sha256 "1e1280dc2b74de3d0a07dfc9edaab72eb82ab5d7b14d7934e3b4b37d235c00ce"

      define_method(:install) do
        bin.install "cashctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/cashctl/releases/download/v0.4.0/cashctl_linux_amd64.tar.gz"
      sha256 "0a561516e516278ebb6623d39f87e9097816c148fa88c18c917d41e9569d0426"
      define_method(:install) do
        bin.install "cashctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/cashctl/releases/download/v0.4.0/cashctl_linux_arm64.tar.gz"
      sha256 "59ccc86243f2d68d2adb46bf4ed4dddd47401dc01e7d19135e6ff9828aa2ca56"
      define_method(:install) do
        bin.install "cashctl"
      end
    end
  end

  conflicts_with "cashctl-rc"

  test do
    system "#{bin}/cashctl", "version"
  end
end
