# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncli < Formula
  desc "A single binary for running and operating Nostr relays: serve, stream, sync, inspect, search, export, and mine events."
  homepage "https://github.com/ohstr/ncli"
  version "0.1.0"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohstr/ncli/releases/download/v0.1.0/ncli_darwin_amd64.tar.gz"
      sha256 "635af8f95b932690ce3aa4a2839bd3cbab22c2435f78f4481aa0cfaab994f1a7"

      define_method(:install) do
        bin.install "ncli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohstr/ncli/releases/download/v0.1.0/ncli_darwin_arm64.tar.gz"
      sha256 "a950ba45fc4be0cd07880a6308e2be3b8e59133f5c2c28bd0ba7d89d45e08202"

      define_method(:install) do
        bin.install "ncli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/ncli/releases/download/v0.1.0/ncli_linux_amd64.tar.gz"
      sha256 "e03e4d7793d83db679392fe7d4aa9a756c8b5e8d08ce3632fc656338d70e09d5"
      define_method(:install) do
        bin.install "ncli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/ncli/releases/download/v0.1.0/ncli_linux_arm64.tar.gz"
      sha256 "2376878324040cd477c7a76a953f50ca8a82249db7340ad1e603c05ce17e3e77"
      define_method(:install) do
        bin.install "ncli"
      end
    end
  end

  test do
    system "#{bin}/ncli", "version"
  end
end
