# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncli < Formula
  desc "A single binary for running and operating Nostr relays: serve, stream, sync, inspect, search, export, and mine events."
  homepage "https://github.com/ohstr/ncli"
  version "0.1.0"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohstr/ncli/releases/download/v0.1.0/ncli_darwin_amd64.tar.gz"
      sha256 "90fb5ca000e75b7ee97bfa52b047696114881da0975fe798d1483209763f4d60"

      define_method(:install) do
        bin.install "ncli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohstr/ncli/releases/download/v0.1.0/ncli_darwin_arm64.tar.gz"
      sha256 "af002354280982abd9ad1d9a67cd9d28a6b746ef08005679076aa22c10506486"

      define_method(:install) do
        bin.install "ncli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/ncli/releases/download/v0.1.0/ncli_linux_amd64.tar.gz"
      sha256 "1d3f0f9fad7b68c996f0555a6b5be92fd3c9291b2c1bc33138294ca6175639b2"
      define_method(:install) do
        bin.install "ncli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/ncli/releases/download/v0.1.0/ncli_linux_arm64.tar.gz"
      sha256 "6c26831a43f00e20021268bc5604125d1aa3b9b16c2b9c50b72d7ff8dd1021f9"
      define_method(:install) do
        bin.install "ncli"
      end
    end
  end

  test do
    system "#{bin}/ncli", "version"
  end
end
