# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NcliRc < Formula
  desc "Release-candidate build of ncli -- see the ncli formula for stable installs."
  homepage "https://github.com/ohstr/ncli"
  version "0.8.0-rc.1"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohstr/ncli/releases/download/v0.8.0-rc.1/ncli_darwin_amd64.tar.gz"
      sha256 "6d0f3a09fb222e216da8e638e83ed7bae5d55f837da8f83e8fedb0bf3eefe4c3"

      define_method(:install) do
        bin.install "ncli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohstr/ncli/releases/download/v0.8.0-rc.1/ncli_darwin_arm64.tar.gz"
      sha256 "0496f3afaa7a11e0183077414d694743363d5f74479a9f0b9dbc05c3d7ebb588"

      define_method(:install) do
        bin.install "ncli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/ncli/releases/download/v0.8.0-rc.1/ncli_linux_amd64.tar.gz"
      sha256 "340d81365c5521d9ec850f48c5ba190cb52d7d53c6eea0ecbe9dbed80a3d2597"
      define_method(:install) do
        bin.install "ncli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/ncli/releases/download/v0.8.0-rc.1/ncli_linux_arm64.tar.gz"
      sha256 "bee7cbf36ccb5f497fd953e6c2c71299f4a435ffe0b7562b3c37208ce18ce2ff"
      define_method(:install) do
        bin.install "ncli"
      end
    end
  end

  conflicts_with "ncli"

  test do
    system "#{bin}/ncli", "version"
  end
end
